### PR TITLE
Osprey Tuneup + Wholesale Ship Missing Path Fix

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request

<details>
<summary>The Osprey Stuff:</summary>

Tunes up the Osprey with modern /tg/ fixtures, in the style of previous tuneups of mine. 
~~I am not being held against my will to work on random Nanotrasen projects, what, no, that'd be crazy.~~
New Osprey:

Gameplay changes are as follows:
The QM now has an office, which comes with it's own APC and power drain,
Science has a space to actually make use of their RND boards without tearing stuff down, which cargo shares without having to walk inside,
One set of 30 plasma sheets has been exchanged for an (empty) superpacman. No uranium spawns on the ship,
Battery loopback has been OBLITERATED,
Janitor has a bunch of extra dust to clean up,
Some differently-layered wires for the engineers to scratch their heads at exist now,
All those goofy-ass firelock-under-doors are gone. Smartfirelocks + Airlocks do not mix.

</details>

<details>
<summary>The Missing Path Stuff:</summary>

Fixes missing paths on EVERY shuttle in the voidcrew folder and replaces as many windows as I noticed with their spawner counterparts. `Kill. Maim. Slaughter.`
Fixes up the wiring on one specific one, muses on some wacky tobacky stuff I unearthed (See the first commit's description!)

</details>

## Why It's Good For The Game
Contributes to #18
## Changelog
:cl:
add: The Osprey has been tuned up!
fix: All missing paths have been addressed (by hand, not by an updatepaths script.)
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
Hate to do this to you, but can you replace all the station areas with dedicated ship areas

**Comment by unit0016** [comment]
> Hate to do this to you, but can you replace all the station areas with dedicated ship areas

long time no see friend! Course, just found out they *were* implemented (but only for the box whiteship, pFFT)
Gimme a hot second, I've got this.

**Comment by ZephyrTFA** [comment]
> > Hate to do this to you, but can you replace all the station areas with dedicated ship areas
> 
> long time no see friend! Course, just found out they _were_ implemented (but only for the box whiteship, pFFT) Gimme a hot second, I've got this.

You couldn't live with your failures, where did that bring you?
Back to me.

**Comment by unit0016** [comment]
in honor of my discovery during the first commit i should do the bead next honestly

**Review by JohnFulpWillard — APPROVED** [review]
You did everything and more in this PR, thank you

**Comment by JohnFulpWillard** [comment]
> Apparently voidcrew made a version of the NTSV Bubble for combat, and it was just.. dropped in a direct-to-master commit?
Apparently striketester made this modification (nano_bead) and I just heard nothing about it.  There's also a suspiciously similarly laid out ship in the thunderbird. Counting these with the others, (Shiptest (Pre-And Post Baytiles), Beestation, And Monkestation) How many Bubbles are there? Can we go into the Bubbleverse? An NTSV Bubble No Way Home?
Iunno, but it's still amusing to think my dinky little creation's spread so far, with or without my help.

yep i understand (no i dont (what the hell lol))

**Pull request merged**
